-- =============================================================
-- OBSCURIUM - schema.sql
-- PostgreSQL / Supabase
--
-- Baseado no ZIP do projeto e no TCC enviado.
--
-- Contém:
--   5 regiões
--   27 unidades federativas
--   77 arquivos HTML de lendas realmente existentes no ZIP
--   usuários
--   perfis
--
-- As imagens continuam em SRC/img/. O banco guarda somente o
-- caminho relativo do arquivo.
--
-- O TCC prevê 81 lendas, mas o ZIP contém 77 arquivos HTML.
-- Não foram inventadas páginas que não existem.
--
-- Dois arquivos existentes no ZIP não possuem UF definida no
-- apêndice do TCC:
--   Norte/vitoria-regia.html
--   Nordeste/homem_do_saco.html
-- Nesses dois registros, estado_id fica NULL.
-- =============================================================

DROP TABLE IF EXISTS perfis CASCADE;
DROP TABLE IF EXISTS usuarios CASCADE;
DROP TABLE IF EXISTS lendas CASCADE;
DROP TABLE IF EXISTS estados CASCADE;
DROP TABLE IF EXISTS regioes CASCADE;

CREATE TABLE regioes (
    id SMALLINT PRIMARY KEY,
    nome VARCHAR(30) NOT NULL UNIQUE,
    sigla VARCHAR(2) NOT NULL UNIQUE
);

CREATE TABLE estados (
    id SMALLINT PRIMARY KEY,
    regiao_id SMALLINT NOT NULL
        REFERENCES regioes(id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,
    nome VARCHAR(40) NOT NULL UNIQUE,
    sigla CHAR(2) NOT NULL UNIQUE,
    capital VARCHAR(60) NOT NULL
);

CREATE TABLE lendas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    estado_id SMALLINT
        REFERENCES estados(id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,
    nome VARCHAR(150) NOT NULL,
    slug VARCHAR(180) NOT NULL,
    descricao TEXT,
    imagem_path VARCHAR(255),
    pagina_path VARCHAR(255) NOT NULL UNIQUE,
    criado_em TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    atualizado_em TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_lendas_estado_slug UNIQUE (estado_id, slug)
);

CREATE INDEX idx_estados_regiao_id ON estados(regiao_id);
CREATE INDEX idx_lendas_estado_id ON lendas(estado_id);
CREATE INDEX idx_lendas_nome_lower ON lendas (LOWER(nome));

CREATE TABLE usuarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    criado_em TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE perfis (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id BIGINT NOT NULL UNIQUE
        REFERENCES usuarios(id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    foto_path VARCHAR(255)
);

-- =============================================================
-- 5 REGIÕES
-- =============================================================

INSERT INTO regioes (id, nome, sigla) VALUES
    (1, 'Norte', 'N'),
    (2, 'Nordeste', 'NE'),
    (3, 'Centro-Oeste', 'CO'),
    (4, 'Sudeste', 'SE'),
    (5, 'Sul', 'S');

-- =============================================================
-- 27 UNIDADES FEDERATIVAS
-- =============================================================

INSERT INTO estados (id, regiao_id, nome, sigla, capital) VALUES
    (1, 1, 'Acre', 'AC', 'Rio Branco'),
    (2, 2, 'Alagoas', 'AL', 'Maceió'),
    (3, 1, 'Amapá', 'AP', 'Macapá'),
    (4, 1, 'Amazonas', 'AM', 'Manaus'),
    (5, 2, 'Bahia', 'BA', 'Salvador'),
    (6, 2, 'Ceará', 'CE', 'Fortaleza'),
    (7, 3, 'Distrito Federal', 'DF', 'Brasília'),
    (8, 4, 'Espírito Santo', 'ES', 'Vitória'),
    (9, 3, 'Goiás', 'GO', 'Goiânia'),
    (10, 2, 'Maranhão', 'MA', 'São Luís'),
    (11, 3, 'Mato Grosso', 'MT', 'Cuiabá'),
    (12, 3, 'Mato Grosso do Sul', 'MS', 'Campo Grande'),
    (13, 4, 'Minas Gerais', 'MG', 'Belo Horizonte'),
    (14, 1, 'Pará', 'PA', 'Belém'),
    (15, 2, 'Paraíba', 'PB', 'João Pessoa'),
    (16, 5, 'Paraná', 'PR', 'Curitiba'),
    (17, 2, 'Pernambuco', 'PE', 'Recife'),
    (18, 2, 'Piauí', 'PI', 'Teresina'),
    (19, 4, 'Rio de Janeiro', 'RJ', 'Rio de Janeiro'),
    (20, 2, 'Rio Grande do Norte', 'RN', 'Natal'),
    (21, 5, 'Rio Grande do Sul', 'RS', 'Porto Alegre'),
    (22, 1, 'Rondônia', 'RO', 'Porto Velho'),
    (23, 1, 'Roraima', 'RR', 'Boa Vista'),
    (24, 5, 'Santa Catarina', 'SC', 'Florianópolis'),
    (25, 4, 'São Paulo', 'SP', 'São Paulo'),
    (26, 2, 'Sergipe', 'SE', 'Aracaju'),
    (27, 1, 'Tocantins', 'TO', 'Palmas');

-- =============================================================
-- 77 LENDAS EXISTENTES NO ZIP
-- =============================================================

INSERT INTO lendas (estado_id, nome, slug, descricao, imagem_path, pagina_path) VALUES
    (11, 'Boitatá do Pantanal', 'boitata_do_pantanal', NULL, 'img/Boitatá do Pantanal.png', 'Lendas_Locais/Centro-Oeste/boitata_do_pantanal.html'),
    (12, 'Camisa de Couro', 'camisa_de_couro', NULL, 'img/Camisa de Couro.png', 'Lendas_Locais/Centro-Oeste/camisa_de_couro.html'),
    (9, 'Cruz do Anhanguera', 'cruz_do_anhanguera', NULL, 'img/Cruz do Anhanguera.png', 'Lendas_Locais/Centro-Oeste/cruz_do_anhanguera.html'),
    (7, 'Fantasma do Catetinho', 'fantasma_do_catetinho', NULL, 'img/Fantasma do Catetinho.png', 'Lendas_Locais/Centro-Oeste/fantasma_do_catetinho.html'),
    (7, 'Loira do Palácio da Alvorada', 'loira_do_palacio_da_alvorada', NULL, 'img/Loira do Palácio da Alvorada.png', 'Lendas_Locais/Centro-Oeste/loira_do_palacio_da_alvorada.html'),
    (12, 'Mãe do Ouro', 'mae_do_ouro', NULL, 'img/Mãe do Ouro.png', 'Lendas_Locais/Centro-Oeste/mae_do_ouro.html'),
    (11, 'Minhocão do Pari', 'minhocao_do_pari', NULL, 'img/Minhocão do Pari.png', 'Lendas_Locais/Centro-Oeste/minhocao_do_pari.html'),
    (7, 'Noiva da Ponte JK', 'noiva_da_ponte_jk', NULL, 'img/Noiva da Ponte JK.png', 'Lendas_Locais/Centro-Oeste/noiva_da_ponte_jk.html'),
    (11, 'Pé-de-Garrafa', 'pe-de-garrafa', NULL, 'img/Pé-de-Garrafa.png', 'Lendas_Locais/Centro-Oeste/pe-de-garrafa.html'),
    (9, 'Romãozinho', 'romaozinho', NULL, 'img/Romãozinho.png', 'Lendas_Locais/Centro-Oeste/romaozinho.html'),
    (9, 'Serra dos Pireneus Encantada', 'serra_dos_pireneus', NULL, 'img/Serra dos Pireneus Encantada .png', 'Lendas_Locais/Centro-Oeste/serra_dos_pireneus.html'),
    (12, 'Touro Negro da Serra da Bodoquena', 'touro_negro_da_serra_bodoquena', NULL, 'img/Touro Negro da Serra da Bodoquena.png', 'Lendas_Locais/Centro-Oeste/touro_negro_da_serra_bodoquena.html'),
    (10, 'Ana Jansen', 'ana_jansen', NULL, 'img/Ana Jansen.png', 'Lendas_Locais/Nordeste/ana_jansen.html'),
    (17, 'Assombração do Palácio do Campo das Princesas', 'assombracao_do_palacio_do_campo', NULL, 'img/Assombração do Palácio do Campo das Princesas.png', 'Lendas_Locais/Nordeste/assombracao_do_palacio_do_campo.html'),
    (2, 'Bicho da Usina Uruba', 'bicho_da_usina', NULL, 'img/Bicho da Usina Uruba.png', 'Lendas_Locais/Nordeste/bicho_da_usina.html'),
    (17, 'Boca de Ouro', 'boca_de_ouro', NULL, 'img/Boca de Ouro.png', 'Lendas_Locais/Nordeste/boca_de_ouro.html'),
    (20, 'Botija Encantada', 'botija_encantada', NULL, 'img/Botija Encantada.png', 'Lendas_Locais/Nordeste/botija_encantada.html'),
    (5, 'Caboclo d’Água do Rio São Francisco', 'caboclo_dAgua', NULL, 'img/Caboclo-d''Água-do-Rio-São-Francisco.png', 'Lendas_Locais/Nordeste/caboclo_dAgua.html'),
    (20, 'Cabra Cabriola', 'cabra_cabriola', NULL, 'img/Cabra Cabriola.png', 'Lendas_Locais/Nordeste/cabra_cabriola.html'),
    (5, 'Caipora', 'caipora', NULL, 'img/A Caipora.png', 'Lendas_Locais/Nordeste/caipora.html'),
    (10, 'Carruagem Fantasma de São Luís', 'carruagem_fantasma', NULL, 'img/Carruagem Fantasma de São Luís.png', 'Lendas_Locais/Nordeste/carruagem_fantasma.html'),
    (6, 'Cidade Encantada de Jericoacoara', 'cidade_encantada_de_jericoacoara', NULL, 'img/Cidade_Encantada_de_Jericoacoara.png', 'Lendas_Locais/Nordeste/cidade_encantada_de_jericoacoara.html'),
    (26, 'Cobra da Igreja de São Cristóvão', 'cobra_da_igreja_de_sao_cristovao', NULL, 'img/Cobra da Igreja de São Cristóvão.png', 'Lendas_Locais/Nordeste/cobra_da_igreja_de_sao_cristovao.html'),
    (2, 'Cobra Grande da Lagoa Mundaú', 'cobra_grande_da_lagoa', NULL, 'img/Cobra Grande da Lagoa Mundaú.png', 'Lendas_Locais/Nordeste/cobra_grande_da_lagoa.html'),
    (15, 'Cumade Fulozinha', 'cumade_fulozinha', NULL, 'img/Cumade Fulozinha.png', 'Lendas_Locais/Nordeste/cumade_fulozinha.html'),
    (17, 'Emparedada da Rua Nova', 'emparedada_da_rua_nova', NULL, 'img/Emparedada da Rua Nova.png', 'Lendas_Locais/Nordeste/emparedada_da_rua_nova.html'),
    (NULL, 'Homem do Saco', 'homem_do_saco', NULL, 'img/Papa-Figo_(Homem do Saco).png', 'Lendas_Locais/Nordeste/homem_do_saco.html'),
    (26, 'Mãe d’Água do Rio Vaza-Barris', 'mae_dAgua_do_rio_vaza-barris', NULL, 'img/Mãe d''Água do Rio Vaza-Barris.png', 'Lendas_Locais/Nordeste/mae_dAgua_do_rio_vaza-barris.html'),
    (5, 'Moura Torta', 'moura_torta', NULL, 'img/A Moura Torta.png', 'Lendas_Locais/Nordeste/moura_torta.html'),
    (18, 'Noiva da Ponte Estaiada', 'noiva_da_ponte_estaiada', NULL, 'img/Noiva da Ponte Estaiada.png', 'Lendas_Locais/Nordeste/noiva_da_ponte_estaiada.html'),
    (20, 'Noiva do Forte dos Reis Magos', 'noiva_do_forte_dos_reis_magos', NULL, 'img/Noiva do Forte dos Reis Magos.png', 'Lendas_Locais/Nordeste/noiva_do_forte_dos_reis_magos.html'),
    (15, 'Pedra do Ingá Encantada', 'pedra_do_inga_encantada', NULL, 'img/Pedra do Ingá Encantada.png', 'Lendas_Locais/Nordeste/pedra_do_inga_encantada.html'),
    (6, 'Princesa da Pedra da Galinha Choca', 'princesa_da_pedra_galinha', NULL, 'img/Princesa da Pedra da Galinha Choca.png', 'Lendas_Locais/Nordeste/princesa_da_pedra_galinha.html'),
    (10, 'Rei Sebastião dos Lençóis', 'rei_sebastiao_dos_lencois', NULL, 'img/Rei Sebastião dos Lençóis.png', 'Lendas_Locais/Nordeste/rei_sebastiao_dos_lencois.html'),
    (6, 'Serpente da Lagoa de Messejana', 'serpente_da_lagoa_messejana', NULL, 'img/Serpente_da_Lagoa_de_Messejana.png', 'Lendas_Locais/Nordeste/serpente_da_lagoa_messejana.html'),
    (18, 'Serra da Capivara Encantada', 'serra_da_capivara_encantada', NULL, 'img/Serra da Capivara Encantada.png', 'Lendas_Locais/Nordeste/serra_da_capivara_encantada.html'),
    (15, 'Tesouro da Serra da Borborema', 'tesouro_da_serra_da_borborema', NULL, 'img/Tesouro da Serra da Borborema.png', 'Lendas_Locais/Nordeste/tesouro_da_serra_da_borborema.html'),
    (26, 'Tesouro Encantado do Rio Real', 'tesouro_encantado_do_rio_real', NULL, NULL, 'Lendas_Locais/Nordeste/tesouro_encantado_do_rio_real.html'),
    (1, 'Cobra Grande (Boiúna)', 'boiuna_cobra-grande', NULL, 'img/Cobra Grande (Boiúna).png', 'Lendas_Locais/Norte/boiuna_cobra-grande.html'),
    (4, 'Boto Cor-de-Rosa', 'boto_cor_de_rosa', NULL, 'img/Boto Cor-de-Rosa.png', 'Lendas_Locais/Norte/boto_cor_de_rosa.html'),
    (23, 'Canaima', 'canaima', NULL, 'img/Canaima.png', 'Lendas_Locais/Norte/canaima.html'),
    (14, 'Boiúna (Cobra-Grande)', 'cobra_grande_boiuna', NULL, 'img/Boiúna (Cobra-Grande).png', 'Lendas_Locais/Norte/cobra_grande_boiuna.html'),
    (14, 'Cobra Norato', 'cobra_norato', NULL, 'img/Cobra Norato.png', 'Lendas_Locais/Norte/cobra_norato.html'),
    (4, 'Curupira', 'curupira', NULL, 'img/Curupira.png', 'Lendas_Locais/Norte/curupira.html'),
    (4, 'Iara (Uiara)', 'iara', 'Iara é uma lenda que circula na região do Norte do Brasil, contando a história de uma mulher que se transforma em um ser misterioso após morrer.', 'img/Iara (Mãe-d''Água).png', 'Lendas_Locais/Norte/iara.html'),
    (3, 'Lagoa da Piratuba', 'lagoa_da_piratuba', NULL, 'img/Lagoa da Piratuba.png', 'Lendas_Locais/Norte/lagoa_da_piratuba.html'),
    (27, 'Lobisomem do Jalapão', 'lobisomem_do_jalapao', NULL, 'img/Lobisomem do Jalapão.png', 'Lendas_Locais/Norte/lobisomem_do_jalapao.html'),
    (22, 'Mãe d’Água do Rio Madeira', 'mae_dAgua_do_rio_madeira', NULL, 'img/Mãe d''Água do Rio Madeira.png', 'Lendas_Locais/Norte/mae_dAgua_do_rio_madeira.html'),
    (1, 'Mãe da Mata', 'mae_da_mata', NULL, 'img/Mae da mata.png', 'Lendas_Locais/Norte/mae_da_mata.html'),
    (12, 'Mãe do Ouro', 'mae_do_ouro', NULL, 'img/Mãe do Ouro.png', 'Lendas_Locais/Norte/mae_do_ouro.html'),
    (23, 'Makunaimî e os Frutos Sagrados', 'makunaimi-e-os-frutos', NULL, 'img/Makunaimî e os Frutos Sagrados.png', 'Lendas_Locais/Norte/makunaimi-e-os-frutos.html'),
    (1, 'Mapinguari', 'mapinguari', NULL, 'img/Mapinguari.png', 'Lendas_Locais/Norte/mapinguari.html'),
    (3, 'Matinta Perera', 'matinta_pereira', NULL, 'img/Matinta_Pereira_(Matinta Perera).png', 'Lendas_Locais/Norte/matinta_pereira.html'),
    (23, 'Monte Roraima Encantado', 'monte_roraima_encantado', NULL, 'img/Monte Roraima Encantado.png', 'Lendas_Locais/Norte/monte_roraima_encantado.html'),
    (22, 'Pai da Mata', 'pai_da_mata', NULL, 'img/Pai da Mata.png', 'Lendas_Locais/Norte/pai_da_mata.html'),
    (3, 'Princesa do Cunani', 'princesa_do_cunani', NULL, 'img/A Princesa do Cunani.png', 'Lendas_Locais/Norte/princesa_do_cunani.html'),
    (NULL, 'Vitória-Régia', 'vitoria-regia', NULL, 'img/Vitória-Régia.png', 'Lendas_Locais/Norte/vitoria-regia.html'),
    (25, 'Corpo-Seco', 'corpo-seco', NULL, 'img/Corpo-Seco.png', 'Lendas_Locais/Sudeste/corpo-seco.html'),
    (25, 'Diabo na Garrafa', 'diabo_na_garrafa', NULL, 'img/Diabo na Garrafa.png', 'Lendas_Locais/Sudeste/diabo_na_garrafa.html'),
    (13, 'Fantasma de Chico Rei', 'fantasma_de_chico_rei', NULL, 'img/Fantasma de Chico Rei.png', 'Lendas_Locais/Sudeste/fantasma_de_chico_rei.html'),
    (19, 'Fantasma do Theatro Municipal', 'fantasma_do_theatro_munucipal', NULL, 'img/Fantasma do Theatro Municipal.png', 'Lendas_Locais/Sudeste/fantasma_do_theatro_munucipal.html'),
    (13, 'Gruta do Maquiné Encantada', 'gruta_do_maquine_encantada', NULL, 'img/Gruta do Maquiné Encantada.png', 'Lendas_Locais/Sudeste/gruta_do_maquine_encantada.html'),
    (25, 'Loira do Banheiro', 'loira_do_banheiro', NULL, 'img/Loira do Banheiro.png', 'Lendas_Locais/Sudeste/loira_do_banheiro.html'),
    (19, 'Maldição da Ilha Fiscal', 'maldicao_da_ilha_fiscal', NULL, 'img/Maldição da Ilha Fiscal.png', 'Lendas_Locais/Sudeste/maldicao_da_ilha_fiscal.html'),
    (13, 'Noiva da Serra do Curral', 'noiva_da_serra_do_curral', NULL, 'img/Noiva da Serra do Curral.png', 'Lendas_Locais/Sudeste/noiva_da_serra_do_curral.html'),
    (8, 'Pedra da Cebola Encantada', 'pedra_da_cebola_encantada', NULL, 'img/Pedra da Cebola Encantada.png', 'Lendas_Locais/Sudeste/pedra_da_cebola_encantada.html'),
    (8, 'Sereia de Guarapari', 'sereia_de_guarapari', NULL, 'img/Sereia de Guarapari.png', 'Lendas_Locais/Sudeste/sereia_de_guarapari.html'),
    (19, 'Serpente da Lagoa Rodrigo de Freitas', 'serpente_da_lagoa_rodrigo_de_freitas', NULL, 'img/Serpente da Lagoa Rodrigo de Freitas.png', 'Lendas_Locais/Sudeste/serpente_da_lagoa_rodrigo_de_freitas.html'),
    (8, 'Tesouro dos Jesuítas', 'tesouro_dos_jesuitas', NULL, 'img/Tesouro dos Jesuítas.png', 'Lendas_Locais/Sudeste/tesouro_dos_jesuitas.html'),
    (24, 'Boi de Mamão Encantado', 'boi_de_mamao_encantado', NULL, 'img/Boi de Mamão Encantado.png', 'Lendas_Locais/Sul/boi_de_mamao_encantado.html'),
    (24, 'Bruxa de Itaguaçu', 'bruxa_de_itaguacu', NULL, 'img/Bruxa de Itaguaçu.png', 'Lendas_Locais/Sul/bruxa_de_itaguacu.html'),
    (16, 'Fantasma do Castelinho do Batel', 'fantasma_do_castelinho_do_batel', NULL, 'img/Fantasma do Castelinho do Batel.png', 'Lendas_Locais/Sul/fantasma_do_castelinho_do_batel.html'),
    (16, 'Gralha-Azul Encantada', 'gralha-azul_encantada', NULL, 'img/Gralha-Azul Encantada.png', 'Lendas_Locais/Sul/gralha-azul_encantada.html'),
    (24, 'Gruta da Lagoa Encantada', 'gruta_da_lagoa_encantada', NULL, 'img/Gruta da Lagoa Encantada.png', 'Lendas_Locais/Sul/gruta_da_lagoa_encantada.html'),
    (21, 'Negrinho do Pastoreio', 'negrinho_do_pastoreiro', NULL, 'img/Negrinho do Pastoreio.png', 'Lendas_Locais/Sul/negrinho_do_pastoreiro.html'),
    (21, 'Noiva da Lagoa dos Barros', 'noiva_da_lagoa_dos_barros', NULL, 'img/Noiva da Lagoa dos Barros.png', 'Lendas_Locais/Sul/noiva_da_lagoa_dos_barros.html'),
    (21, 'Salamanca do Jarau', 'salamanca_do_jarau', NULL, 'img/Salamanca do Jarau.png', 'Lendas_Locais/Sul/salamanca_do_jarau.html');

-- =============================================================
-- CONFERÊNCIA
-- =============================================================
-- SELECT COUNT(*) AS total_regioes FROM regioes;
-- SELECT COUNT(*) AS total_estados FROM estados;
-- SELECT COUNT(*) AS total_lendas FROM lendas;
--
-- Lendas sem UF atribuída no TCC:
-- SELECT id, nome, pagina_path
-- FROM lendas
-- WHERE estado_id IS NULL;
--
-- Quantidade por região:
-- SELECT r.nome AS regiao, COUNT(l.id) AS total
-- FROM regioes r
-- LEFT JOIN estados e ON e.regiao_id = r.id
-- LEFT JOIN lendas l ON l.estado_id = e.id
-- GROUP BY r.id, r.nome
-- ORDER BY r.id;
--
-- Quantidade por estado:
-- SELECT e.nome AS estado, e.sigla, COUNT(l.id) AS total
-- FROM estados e
-- LEFT JOIN lendas l ON l.estado_id = e.id
-- GROUP BY e.id, e.nome, e.sigla
-- ORDER BY e.id;
